language: android
android:
  components:
    - platform-tools
    - build-tools-26.0.2
    - android-26

script:
   - ./gradlew build connectedCheck

branches:
        only:
                - master
script:
  - chmod +x ./gradlew  
